name: Deploy in VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone git@github.com:AntonioRdC/reservation-manager.git
            cd reservation-manager
            pnpm i
            pnpm build
            pm2 delete reservationManager || true
            pm2 start pnpm --name reservationManager -- start
