name: Deploy Node.js App to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar dependências
        run: npm install --production

      - name: Exportar variáveis de ambiente para o banco de dados
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV

      - name: Rodar db:generate
        run: npm run db:generate

      - name: Rodar db:migrate
        run: npm run db:migrate

      - name: Criar pacote ZIP para o Beanstalk
        run: zip -r app.zip * -x "node_modules/*" ".git/*" ".github/*"

      - name: Enviar ZIP para S3
        run: aws s3 cp app.zip s3://${{ secrets.S3_BUCKET_NAME }}/app.zip
