name: Deploy in VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Carrega NVM
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH
            export PATH=$(npm bin -g):$PATH

            rm -rf reservation-manager
            git clone git@github.com:AntonioRdC/reservation-manager.git
            cp .env reservation-manager/
            cd reservation-manager
            pnpm i
            pnpm build
            pm2 delete reservationManager || true
            pm2 start pnpm --name reservationManager -- start
