name: Deploy Node.js App to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Criar pacote ZIP para o Beanstalk
        run: zip -r app.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: Enviar ZIP para S3
        run: aws s3 cp app.zip s3://${{ secrets.S3_BUCKET_NAME }}/app.zip
